steps:
# Step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest || exit 0'
  ]
# Step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest',
   '.'
  ]
  #dir: 'my-app-vue'
# Step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '*']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
  - 'CLOUDSDK_CONTAINER_CLUSTER=vitaehr'
# Step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'vitaehr', 
   'vitaehr=gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west4'
  - 'CLOUDSDK_CONTAINER_CLUSTER=vitaehr'
  # Push the image to Google Container Registry with the latest tag
images: [
   'gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest'
  ]
