apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "vita"
  namespace: "default"
  labels:
    app: "vita"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "vita"
  template:
    metadata:
      labels:
        app: "vita"
    spec:
      containers:
      - name: "vita"
        image: "gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest"
