apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "vita"
  namespace: "default"
  labels:
    app: "vita"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "vita"
  template:
    metadata:
      labels:
        app: "vita"
    spec:
      containers:
      - name: "gcp-final-sha256-1"
          image: "gcr.io/regal-campaign-385913/github.com/nursahmican/gcp-final:latest"
